dist: xenial

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - TEST_DEVICE_ID=emulator-5554
    - APK_URL=https://github.com/michalkielan/AndroidDummyApp/releases/download/0.0.1/app-debug.apk

matrix:
  include:
    - name: "Pylint 3.6"
      language: python
      python:
        - "3.6"
      install:
        - pip install flake8
      script:
        - flake8 simpleadb tests

    - name: "Python 3.6, API 24"
      language: android
      jdk: oraclejdk11
      install:
        - pip install python-coveralls pytest tox-travis
      env: PYTHON_VERSION=3.6.0 TOXENV=py36 ANDROID_API=android-24
      android:
        components:
         - build-tools
         - extra-android-m2repository
         - $ANDROID_API
         - sys-img-x86-$ANDROID_API
         - sys-img-armeabi-v7a-$ANDROID_API
      before_install:
        - pyenv install --list
        - pyenv install $PYTHON_VERSION
        - pyenv global $PYTHON_VERSION
        - android list target
        - echo no | android create avd --force -n test -t $ANDROID_API --abi armeabi-v7a -c 100M
        - emulator -avd test -no-skin -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - wget $APK_URL
        - python setup.py install
        - tox
      after_success:
        - coveralls
