language: android
jdk: oraclejdk11
sudo: required

python:
  - "3.7"

addons:
  apt:
    packages:
      python-logilab-common

android:
  components:
    - build-tools-26.0.2
    - android-24
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-24
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-android-28

  licenses:
   - 'android-sdk-license-.+'

install:
  - sudo pip install pylint

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_script:
  - pylint simpleadb.py adbprocess.py
  - android list target
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a -c 100M
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - git clone https://github.com/michalkielan/AndroidDummyApp.git
  - cd AndroidDummyApp
  - ./gradlew build
  - find . | grep apk 
  - cd ..
  - cp AndroidDummyApp/app/build/outputs/apk/debug/app-debug.apk .
  - pytest test_simpleadb.py
