language: android
jdk: oraclejdk11
sudo: required

python:
  - "3.7"

addons:
  apt:
    packages:
      python-logilab-common

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-26

  licenses:
   - 'android-sdk-license-.+'

install:
  - sudo pip install pylint

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_script:
  - pylint simpleadb.py adbprocess.py
  - android list target
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a -c 100M
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - pytest test_simpleadb.py
