sudo: required
dist: trusty

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - TEST_DEVICE_ID=emulator-5554
    - DUMMY_APK_URL=https://github.com/michalkielan/AndroidDummyApp/releases/download/0.0.1/app-debug.apk
matrix:
  include:
    - name: "Pylint 3.6"
      language: python
      python:
        - "3.6"
      install:
        - pip install pylint
      script:
        - pylint simpleadb
        - pylint --errors-only tests

    - name: "Python 3.5, API 24"
      env: PYTHON_VERSION=3.5.0 TOXENV=py35 ANDROID_API=android-24
      language: android
      jdk: oraclejdk11
      install:
        - sudo pip install python-coveralls pytest tox-travis
      android:
        components:
         - build-tools
         - $ANDROID_API
         - extra-android-m2repository
         - sys-img-x86-$ANDROID_API
         - sys-img-armeabi-v7a-$ANDROID_API
      before_script:
        - pyenv install $PYTHON_VERSION
        - pyenv global $PYTHON_VERSION
        - android list target
        - echo no | android create avd --force -n test -t $ANDROID_API --abi armeabi-v7a -c 100M
        - emulator -avd test -no-skin -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - wget $DUMMY_APK_URL
        - python setup.py install
        - tox
       after_success:
         - coveralls
                     
          #    - name: "Python 3.6, API 24"
          #      env: PYTHON_VERSION=3.6.0 TOXENV=py36 ANDROID_API=android-24
          #      language: android
          #      jdk: oraclejdk11
          #      install:
          #        - sudo pip install python-coveralls pytest tox-travis
          #      android:
          #        components:
          #         - build-tools
          #         - $ANDROID_API
          #         - extra-android-m2repository
          #         - sys-img-x86-$ANDROID_API
          #         - sys-img-armeabi-v7a-$ANDROID_API
          #      before_script:
          #        - pyenv install $PYTHON_VERSION
          #        - pyenv global $PYTHON_VERSION
          #        - android list target
          #        - echo no | android create avd --force -n test -t $ANDROID_API --abi armeabi-v7a -c 100M
          #        - emulator -avd test -no-skin -no-window &
          #        - android-wait-for-emulator
          #        - adb shell input keyevent 82 &
          #      script:
          #        - wget $DUMMY_APK_URL
          #        - python setup.py install
          #        - tox
          #       after_success:
          #         - coveralls
          #                     
          #    - name: "Pypy 3.5, API 24"
          #      env: PYTHON_VERSION=pypy3.5-5.8.0 TOXENV=pypy35 ANDROID_API=android-24
          #      language: android
          #      jdk: oraclejdk11
          #      install:
          #        - sudo pip install python-coveralls pytest tox-travis
          #      android:
          #        components:
          #         - build-tools
          #         - $ANDROID_API
          #         - extra-android-m2repository
          #         - sys-img-x86-$ANDROID_API
          #         - sys-img-armeabi-v7a-$ANDROID_API
          #      before_script:
          #        - pyenv install $PYTHON_VERSION
          #        - pyenv global $PYTHON_VERSION
          #        - android list target
          #        - echo no | android create avd --force -n test -t $ANDROID_API --abi armeabi-v7a -c 100M
          #        - emulator -avd test -no-skin -no-window &
          #        - android-wait-for-emulator
          #        - adb shell input keyevent 82 &
          #      script:
          #        - wget $DUMMY_APK_URL
          #        - python setup.py install
          #        - tox
          #       after_success:
          #         - coveralls
