on: [push]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21]
        python-version: ["3.6", "3.8"]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: |
          reactivecircus/android-emulator-runner@v2
          actions/setup-python@v3
        with:
          api-level: ${{ matrix.api-level }}
          python-version: ${{ matrix.python-version }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            echo "start job 1"
            adb --version
            adb devices
            python --version
            python3 --version

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          python-version: ${{ matrix.python-version }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script:
            echo "start job 2"
            python --version
            adb --version
            adb devices
            python --version
            python3 --version
