#
# file build.yml
#
# SPDX-FileCopyrightText: (c) 2022 Michal Kielan
#
# SPDX-License-Identifier: GPL-3.0-only
#

---
name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build flake8 pylint pytest setuptools sphinx sphinx-rtd-theme wget interruptingcow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pylint
        run: |
          pylint simpleadb tests --errors-only
          pylint simpleadb tests --errors-only --exit-zero
          flake8 simpleadb tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 simpleadb tests --count --exit-zero --statistics

      - name: Doc
        run: |
          sphinx-build -b html doc build

      - name: Install
        run: |
          python -m build
          pip install .
