#
# file tests.yml
#
# SPDX-FileCopyrightText: (c) 2022 Michal Kielan
#
# SPDX-License-Identifier: GPL-3.0-only
#

---
name: tests

on: [push, pull_request]

env:
  ENVIRONMENT: GITHUB_WORKFLOWS
  ADB_INSTALL_TIMEOUT: 8
  TEST_DEVICE_ID: emulator-5554
  ROOTABLE_DEVICE: 1


jobs:
  tests:
    timeout-minutes: 30
    runs-on: macos-13
    strategy:
      matrix:
        api-level: [27]
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage wget interruptingcow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: |
              -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: |
              -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: >
            adb wait-for-device
            &&
            adb shell 'while [ -z "$(getprop sys.boot_completed)" ]; do sleep 1; done'
            &&
            adb shell input keyevent 82
            &&
            coverage run --source=simpleadb -m pytest -v tests;
            TEST_EXIT_CODE=$?;
            echo "=== Starting emulator cleanup ===";
            adb emu kill || echo "ADB kill failed - proceeding to force kill";
            pkill -9 -f "emulator" || true;
            pkill -9 -f "qemu" || true;
            pkill -9 -f "adb" || true;
            pkill -9 -f "crashpad_handler" || true;
            echo "=== Remaining processes ===";
            ps aux | grep -E 'qemu|emulator' || true;
            exit $TEST_EXIT_CODE

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
